name: Test PR

on: pull_request

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - uses: actions/checkout@v4
      - run: poetry install --no-interaction --no-root
      - run: poetry run test
